# i3blocks config file
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks
#
# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.
#command=/usr/lib/i3blocks/$BLOCK_NAME
command=/usr/local/libexec/i3blocks/$BLOCK_NAME
separator_block_width=15
markup=none
# Part 1
[i3-focusedwindow]
label=
command=/home/otavio/.config/i3/scripts/i3-focusedwindow 100
interval=persist

[mediaplayer]
label=♪ 
command=/home/otavio/.config/i3/scripts/mediaplayer
instance=Spotube
interval=5
signal=10

# [cava]
# command=/home/otavio/.config/i3/scripts/cava
# # command=cava
# interval=persist
#
#if you prefer automatic updating
[volume-pulseaudio]
command=/home/otavio/.config/i3/scripts/volume-pulseaudio 
interval=once
signal=1
# click = 3:super+pavucontrol -t 3 -m
# SUBSCRIBE=1
# USE_ALSA_NAME=1




#if you prefer updating only when signaled
# [volume-pulseaudio]
# command=$SCRIPT_DIR/volume-pulseaudio
# interval=once
# signal=1
# USE_ALSA_NAME=1

[cpu_usage]
command=/home/otavio/.config/i3/scripts/cpu_usage
interval=10
LABEL= 
#min_width=CPU: 100.00%
#T_WARN=50
#T_CRIT=80
#DECIMALS=2
#COLOR_NORMAL=#EBDBB2
#COLOR_WARN=#FFFC00
#COLOR_CRIT=#FF0000

[memory]
command=/home/otavio/.config/i3/scripts/memory
label= 
interval=30
[disk]
command=/home/otavio/.config/i3/scripts/disk
LABEL=🖴 
#DIR=$HOME
#ALERT_LOW=10
interval=30


[calendar]
label=
command=date '+%d/%m/%Y'
interval=5

[time]
command=date '+%H:%M'
interval=5

# [audio]
# label=
# interval=5

# [bandwidth]
# instance=wlp3s0;in
# label=
# interval=1

# [bandwidth]
# instance=wlp3s0;out
# label=
# interval=1

# [battery]
# label=
# instance=0
# interval=5

# Part 2

#[bluetooth]
#label=
#interval=10

#[brightness]
#label=
#interval=5

#[countdown]
#instance=tomorrow 05:00:00
#label=
#interval=1

# Part 3

#[cpu]
#label=
#interval=2

#[datetime]
#label=
#interval=5

#[display]
#label=
#interval=5

# Part 4
#[feed]
#instance=http://goo.gl/bR2hcp
#label=
#interval=60

#[firewall]
#label=
#interval=10

#[ip-address]
#label=
#interval=60

# Part 5

#[keystate]
#label=
#instance=caps
#interval=1

#[keystate]
#label=
#instance=num
#interval=1

#[launcher]
#label=
#interval=once

#[load]
#label=
#interval=10

# Part 6

#[locale]
#label=
#interval=once

#[mail]
#label=
#instance=~/.gmx-private
#interval=60

#[memory]
#label=
#instance=mem;free
#interval=30

#[memory]
#label=
#instance=swap;total
#interval=30

# Part 7

#[microphone]
#label=
#interval=5

#[network]
#label=
#instance=enp4s0f2
#interval=10

#[network]
#label=
#instance=wlp3s0
#interval=10

#[packages]
#label=
#interval=300

# Part 8

#[playerctl]
#label=
#instance=rhythmbox
#interval=5

#[process]
#instance=http
#label=
#interval=10

#[space]
#label=
#interval=30

#[space]
#label=
#instance=/pub
#interval=30

# Part 9

#[ssid]
#label=
#interval=60

#[temperature]
#instance=Core
#label=
#interval=5

#[user]
#label=
#interval=once

# Part 10

#[vpn]
#label=
#interval=5

#[weather]
#instance=2910831
#interval=60

#[webcam]
#label=
#interval=5

# Part 11
#[usb]
#instance=PhotoSmart
#label=
#interval=10

#[trash]
#label=
#interval=10

#[cmus]
#command=~/.i3-blocks/blocks/scroll $BLOCK_NAME
#label=
#markup=pango
#interval=repeat

# Part 12

# [window]
# command=~/.i3-blocks/blocks/scroll $BLOCK_NAME
# label=
# markup=pango
# interval=repeat

# [keymap]
# label=
# interval=10i
