font=JetBrains Mono NF:size=17
terminal=alacritty
prompt="> "
layer=overlay
lines=15
width=75
icon-theme=Adawita
dpi-aware=yes
inner-pad=10
horizontal-pad=40
vertical-pad=15
match-counter=yes

[border]
radius=20
width=0

[colors]
background=000000d5
text=d4be98ff
; text=e3e3e3dd
prompt=458588ff
; prompt=c6c6c6ff
placeholder=919191ff
input=d4be98ff
; input=e3e3e3ff
match=d79921ff
; match=cac6c5ff
selection=5e5546ff
; selection=c6c6c687
selection-text=d4be98ff
; selection-text=e3e3e3ff
selection-match=d79921ff
; selection-match=cac6c5ff
counter=919191ff
; border=c6c6c677
border=c6c6c600
; include=~/.config/fuzzel/themes/noctalia
