################ Executions
exec-once = waybar
# exec-once = DankMaterialShell
# exec-once = swww-daemon
# exec-once = swww img ~/Pictures/wallpapers/terra3.png --resize crop
exec-once = swaybg -i ~/Pictures/wallpapers/cobra2.png -m fill
# exec-once = hypridle
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
# exec-once = /home/otavio/.cargo/bin/sleepwatcher-rs & > ~/sleep.log 
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = ~/.local/scripts/workday.sh
# exec-once = swayosd-server &
exec-once = syshud &
exec-once = gammastep -l 29.1913:54.8656
exec-once = swaync
# exec-once = mako
# exec-once = autotiling
# exec-once = dms run
# exec-once = echo "@define-color background rgba(0,0,0,0.78);" > ~/.config/waybar/waybar.css
# exec-once = qs -p $noc
