general {
    hide_cursor = true
}

background {
    monitor =
    color = rgba(000000ff)
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 2
    outer_color = rgb(ffffff)
    inner_color = rgb(000000)
    font_color = rgb(ffffff)
    position = 0, 0
    halign = center
    valign = center
}
