input {
    kb_layout = br
    kb_options = grp:alt_space_toggle
    repeat_delay = 250
    repeat_rate = 35
    follow_mouse = 1
    touchpad {
        natural_scroll = true
        tap-to-click = true
    }
}

