# Window rules
windowrulev2 = float, title:.*DEBUG.*
windowrulev2 = float, class:^(Blueberry.py)$
windowrulev2 = float, class:^(nl.hjdskes.gcolor3)$
windowrulev2 = float, class:^(Nl.hjdskes.gcolor3)$
windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = float, class:^(Xfce4-settings-manager)$
windowrulev2 = float, class:^(Xfce4-taskmanager)$
windowrulev2 = float, title:^(Places)$
windowrulev2 = float, title:^(Library)$
windowrulev2 = float, title:^(library)$
windowrulev2 = float, title:^(calcurse)$
windowrulev2 = float, title:^(pop-up)$
windowrulev2 = float, title:^(Preferences)$
windowrulev2 = float, title:^(setup)$
windowrulev2 = noborder, onworkspace:w[t1]
windowrulev2 = noborder, title:^(wired)$
windowrulev2 = idleinhibit fullscreen, class:^(*)$
windowrulev2 = idleinhibit fullscreen, title:^(*)$
windowrulev2 = idleinhibit fullscreen, fullscreen:1

layerrule = blur, mako
layerrule = blur, notifications
layerrule = ignorezero, notifications
layerrule = blur, waybar
layerrule = blur, launcher
layerrule = ignorezero, launcher
layerrule = ignorealpha 0.5, launcher
layerrule = blur, swayosd
layerrule = ignorezero, swayosd
layerrule = ignorealpha 0.5, swayosd
