#!/usr/bin/env bash


options="Lutris\nCalibre\nDiscord\nMinecraft\nSpotify"

chosen=$(echo -e "$options" | rofi -dmenu -i -p "Select")

case "$chosen" in
    Lutris)
        lutris ;;
    Calibre)
        calibre ;;
    Discord)
        discord ;;
    Minecraft)
        minecraft-launcher ;;
    Spotify)
        env LD_PRELOAD=/usr/lib/spotify-adblock.so spotify --uri=%U ;;
esac
