#!/bin/bash

case "${1}" in
    "next")
        current=$(powerprofilesctl get)
        case $current in
            "power-saver") powerprofilesctl set balanced ;;
            "balanced") powerprofilesctl set performance ;;
            "performance") powerprofilesctl set power-saver ;;
        esac
        pkill -SIGRTMIN+4 i3status-rs
        ;;
    "icon")
        current=$(powerprofilesctl get)
        case $current in
            "power-saver") echo "PS 󱃍" ;;
            "balanced") echo "B 󰾅" ;;
            "performance") echo "PE 󰓅" ;;
        esac
        ;;
    "tooltip")
        powerprofilesctl get
        ;;
esac
