# Colors (Everforest Dark)
general.import = [
  # "~/.config/alacritty/gruvbox.toml",
  "~/.config/alacritty/posterpole.toml",
]

[env]
TERM = "xterm-256color" 

[mouse]
hide_when_typing = true

[font]
normal = { family = "CaskaydiaMonoNerdFont", style = "Regular" }
# normal = { family = "HackNerdFont", style = "Regular" }
size = 12.5

[window]
# padding = { x = 7, y = 7 }
# opacity = 0.8
