# Colors (Everforest Dark)
import = [
  "~/.config/alacritty/gruvbox.toml",
]

[mouse]
hide_when_typing = true
[font]
normal = { family = "CaskaydiaMonoNerdFont", style = "Regular" }
# normal = { family = "HackNerdFont", style = "Regular" }
size = 11

