# Colors (Everforest Dark)
general.import = [
  "~/.config/alacritty/gruvbox.toml",
  # "~/.config/alacritty/catppuccin-mocha.toml",
  # "~/.config/alacritty/posterpole.toml",
]

[colors.primary]
background = "#000000"

[env]
TERM = "xterm-256color" 

[mouse]
hide_when_typing = true

[terminal]
# shell = { program = "/bin/zsh", args = ["-c", "tmux new -A -s temp_$$ && tmux kill-session -t temp_$$"] }
shell = { program = "/bin/zsh", args = ["-c", "trap 'tmux kill-session -t temp_$$' EXIT; tmux new -A -s temp_$$"] }


[font]
# normal = { family = "CaskaydiaMonoNerdFont", style = "Regular" }
# normal = { family = "UbuntuMonoNerdFont", style = "Regular" }
normal = { family = "JetBrainsMono", style = "Regular" }
# normal = { family = "HackNerdFont", style = "Regular" }
size = 15

[window]
dynamic_title = true
# opacity = 0.7
