# Colors (Everforest Dark)
general.import = [
  "~/.config/alacritty/gruvbox.toml",
  # "~/.config/alacritty/catppuccin-mocha.toml",
  # "~/.config/alacritty/posterpole.toml",
]

[colors.primary]
background = "#000000"

[env]
TERM = "xterm-256color" 

[mouse]
hide_when_typing = true

[terminal]
# shell = { program = "/bin/zsh", args = ["-c", "tmux new -A -s temp_$$ && tmux kill-session -t temp_$$"] }
# shell = { program = "/bin/fish", args = ["-c", "trap 'tmux kill-session -t temp_$fish_pid' EXIT; tmux new -A -s temp_$fish_pid"] }
shell = { program = "/bin/fish", args = ["-c", "fish ~/.local/scripts/tmux-new-kill.fish"] }


[font]
normal = { family = "CaskaydiaCove NFM", style = "Regular" }
# normal = { family = "UbuntuMonoNerdFont", style = "Regular" }
# normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
# normal = { family = "HackNerdFont", style = "Regular" }
size = 15

[window]
dynamic_title = true
opacity = 0.85
