# Colors (Leaf Dark Theme)
[colors]

  # Default colors
  [colors.primary]
    background = "0x000000" # leaf_dark_0
    foreground = "0xebdbb2" # leaf_light_1

  # Normal colors
  [colors.normal]
    black   = "0x1E1B1F"   # leaf_dark_1
    red     = "0xCD6169"   # leaf_red_0
    green   = "0x83B28A"   # leaf_green_0
    yellow  = "0xE5BF79"   # leaf_yellow_0
    blue    = "0x5EA7E3"   # leaf_blue_0
    magenta = "0x9E77BD"   # leaf_purple_0
    cyan    = "0x51AEB9"   # leaf_aqua_0
    white   = "0xA0A19D"   # leaf_light_6

  # Bright colors
  [colors.bright]
    black   = "0x4F4D4E"   # leaf_dark_4
    red     = "0x8A424A"   # leaf_red_5
    green   = "0x48624E"   # leaf_green_5
    yellow  = "0x8E754B"   # leaf_yellow_5
    blue    = "0x345E7D"   # leaf_blue_5
    magenta = "0x5F4973"   # leaf_purple_5
    cyan    = "0x326F73"   # leaf_aqua_5
    white   = "0xE1E4DC"   # leaf_light_2

